#!/usr/bin/env bash
# Fixes: curl: (7) Failed to connect to 0 port 80: Connection refused

rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
