#!/usr/bin/env bash
# Script which runs nginx as user
sudo pkill apache2
sudo pkill nginx
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod  700 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
